import type { CatalogCategory, CatalogItem, NodeKind } from "./types";
import { MULTI_CLOUD_CATALOG } from "./catalog-multicloud";
import { PATTERNS_CATALOG } from "./catalog-patterns";
import { NETWORK_CATALOG } from "./catalog-network";

export const KIND_META: Record<
  NodeKind,
  { label: string; accent: string; bg: string; border: string }
> = {
  frontend: {
    label: "Frontend",
    accent: "#a78bfa",
    bg: "rgba(139, 92, 246, 0.12)",
    border: "rgba(167, 139, 250, 0.45)",
  },
  backend: {
    label: "Backend",
    accent: "#60a5fa",
    bg: "rgba(59, 130, 246, 0.12)",
    border: "rgba(96, 165, 250, 0.45)",
  },
  database: {
    label: "Dados",
    accent: "#34d399",
    bg: "rgba(16, 185, 129, 0.12)",
    border: "rgba(52, 211, 153, 0.45)",
  },
  cloud: {
    label: "Infra",
    accent: "#fbbf24",
    bg: "rgba(245, 158, 11, 0.12)",
    border: "rgba(251, 191, 36, 0.45)",
  },
  identity: {
    label: "Identidade",
    accent: "#2dd4bf",
    bg: "rgba(20, 184, 166, 0.12)",
    border: "rgba(45, 212, 191, 0.45)",
  },
  observability: {
    label: "Observabilidade",
    accent: "#fb923c",
    bg: "rgba(249, 115, 22, 0.12)",
    border: "rgba(251, 146, 60, 0.45)",
  },
  integration: {
    label: "Integrações",
    accent: "#818cf8",
    bg: "rgba(99, 102, 241, 0.12)",
    border: "rgba(129, 140, 248, 0.45)",
  },
  deploy: {
    label: "Deploy",
    accent: "#f97316",
    bg: "rgba(249, 115, 22, 0.12)",
    border: "rgba(251, 146, 60, 0.45)",
  },
  security: {
    label: "Security",
    accent: "#f472b6",
    bg: "rgba(236, 72, 153, 0.12)",
    border: "rgba(244, 114, 182, 0.45)",
  },
  network: {
    label: "Network",
    accent: "#38bdf8",
    bg: "rgba(14, 165, 233, 0.12)",
    border: "rgba(56, 189, 248, 0.45)",
  },
};

export const CATALOG: CatalogItem[] = [
  {
    id: "fe-react",
    kind: "frontend",
    label: "React",
    tech: "React",
    description: "SPA client-side",
    category: "framework",
    popularity: 10,
    defaults: { framework: "React", uiLib: "Tailwind", state: "Zustand", rendering: "CSR" },
  },
  {
    id: "fe-next",
    kind: "frontend",
    label: "Next.js",
    tech: "Next.js",
    description: "React com SSR/SSG",
    category: "framework",
    popularity: 10,
    defaults: { framework: "Next.js", uiLib: "Tailwind", state: "Zustand", rendering: "SSR" },
  },
  {
    id: "fe-vue",
    kind: "frontend",
    label: "Vue",
    tech: "Vue",
    description: "SPA progressiva",
    category: "framework",
    popularity: 8,
    defaults: { framework: "Vue", uiLib: "Tailwind", state: "Context API", rendering: "CSR" },
  },
  {
    id: "fe-angular",
    kind: "frontend",
    label: "Angular",
    tech: "Angular",
    description: "Framework opinativo",
    category: "framework",
    popularity: 7,
    defaults: { framework: "Angular", uiLib: "Material UI", state: "Redux", rendering: "CSR" },
  },
  {
    id: "fe-svelte",
    kind: "frontend",
    label: "Svelte",
    tech: "Svelte",
    description: "Compilado, pouco runtime",
    category: "framework",
    popularity: 6,
    defaults: { framework: "Svelte", uiLib: "Tailwind", state: "Context API", rendering: "CSR" },
  },
  {
    id: "fe-sveltekit",
    kind: "frontend",
    label: "SvelteKit",
    tech: "SvelteKit",
    description: "Full-stack Svelte",
    category: "framework",
    popularity: 5,
    defaults: { framework: "SvelteKit", uiLib: "Tailwind", state: "Context API", rendering: "SSR" },
  },
  {
    id: "fe-astro",
    kind: "frontend",
    label: "Astro",
    tech: "Astro",
    description: "Ilhas, zero JS por padrão",
    category: "framework",
    popularity: 6,
    defaults: { framework: "Astro", uiLib: "Tailwind", rendering: "SSG" },
  },
  {
    id: "fe-remix",
    kind: "frontend",
    label: "Remix",
    tech: "Remix",
    description: "React full-stack, loaders",
    category: "framework",
    popularity: 5,
    defaults: { framework: "Remix", uiLib: "Tailwind", state: "Zustand", rendering: "SSR" },
  },
  {
    id: "fe-solid",
    kind: "frontend",
    label: "SolidJS",
    tech: "SolidJS",
    description: "Reatividade sem VDOM",
    category: "framework",
    popularity: 4,
    defaults: { framework: "SolidJS", uiLib: "Tailwind", rendering: "CSR" },
  },
  {
    id: "fe-qwik",
    kind: "frontend",
    label: "Qwik",
    tech: "Qwik",
    description: "Resumability, lazy total",
    category: "framework",
    popularity: 3,
    defaults: { framework: "Qwik", uiLib: "Tailwind", rendering: "SSR" },
  },
  {
    id: "fe-htmx",
    kind: "frontend",
    label: "HTMX",
    tech: "HTMX",
    description: "HTML dinâmico sem build",
    category: "library",
    popularity: 5,
    defaults: { framework: "HTMX", rendering: "SSR" },
  },
  {
    id: "fe-tauri",
    kind: "frontend",
    label: "Tauri",
    tech: "Tauri",
    description: "Desktop apps com web tech",
    category: "framework",
    popularity: 5,
    defaults: { framework: "Tauri", uiLib: "Tailwind", rendering: "CSR" },
  },
  {
    id: "be-fastapi",
    kind: "backend",
    label: "FastAPI",
    tech: "FastAPI",
    description: "Python async",
    category: "framework",
    popularity: 9,
    defaults: { framework: "FastAPI" },
  },
  {
    id: "be-flask",
    kind: "backend",
    label: "Flask",
    tech: "Flask",
    description: "Python minimalista",
    category: "framework",
    popularity: 7,
    defaults: { framework: "Flask" },
  },
  {
    id: "be-django",
    kind: "backend",
    label: "Django",
    tech: "Django",
    description: "Batteries included",
    category: "framework",
    popularity: 8,
    defaults: { framework: "Django" },
  },
  {
    id: "be-express",
    kind: "backend",
    label: "Express",
    tech: "Express",
    description: "Node minimalista",
    category: "framework",
    popularity: 9,
    defaults: { framework: "Express" },
  },
  {
    id: "be-nest",
    kind: "backend",
    label: "NestJS",
    tech: "NestJS",
    description: "Node estruturado",
    category: "framework",
    popularity: 7,
    defaults: { framework: "NestJS" },
  },
  {
    id: "be-spring",
    kind: "backend",
    label: "Spring Boot",
    tech: "Spring Boot",
    description: "Java enterprise",
    category: "framework",
    popularity: 8,
    defaults: { framework: "Spring Boot" },
  },
  {
    id: "be-laravel",
    kind: "backend",
    label: "Laravel",
    tech: "Laravel",
    description: "PHP full-stack",
    category: "framework",
    popularity: 7,
    defaults: { framework: "Laravel" },
  },
  {
    id: "be-gin",
    kind: "backend",
    label: "Go / Gin",
    tech: "Go",
    description: "Go com Gin HTTP",
    category: "framework",
    popularity: 6,
    defaults: { framework: "Gin" },
  },
  {
    id: "be-actix",
    kind: "backend",
    label: "Rust / Actix",
    tech: "Rust",
    description: "Rust com Actix Web",
    category: "framework",
    popularity: 4,
    defaults: { framework: "Actix Web" },
  },
  {
    id: "be-rails",
    kind: "backend",
    label: "Ruby on Rails",
    tech: "Ruby on Rails",
    description: "Convention over configuration",
    category: "framework",
    popularity: 6,
    defaults: { framework: "Rails" },
  },
  {
    id: "be-dotnet",
    kind: "backend",
    label: "ASP.NET Core",
    tech: "C# .NET",
    description: "Microsoft enterprise",
    category: "framework",
    popularity: 7,
    defaults: { framework: "ASP.NET Core" },
  },
  {
    id: "be-hono",
    kind: "backend",
    label: "Hono",
    tech: "Hono",
    description: "Ultra leve, edge-ready",
    category: "framework",
    popularity: 5,
    defaults: { framework: "Hono" },
  },
  {
    id: "be-fiber",
    kind: "backend",
    label: "Fiber (Go)",
    tech: "Fiber",
    description: "Go express-style, fast",
    category: "framework",
    popularity: 4,
    defaults: { framework: "Fiber" },
  },
  {
    id: "be-phoenix",
    kind: "backend",
    label: "Phoenix (Elixir)",
    tech: "Elixir",
    description: "Real-time, concorrência",
    category: "framework",
    popularity: 4,
    defaults: { framework: "Phoenix" },
  },
  {
    id: "be-bun",
    kind: "backend",
    label: "Bun",
    tech: "Bun",
    description: "Runtime JS all-in-one",
    category: "framework",
    popularity: 5,
    defaults: { framework: "Bun" },
  },
  {
    id: "be-denodeploy",
    kind: "backend",
    label: "Deno",
    tech: "Deno",
    description: "Secure JS/TS runtime",
    category: "framework",
    popularity: 4,
    defaults: { framework: "Deno" },
  },
  {
    id: "be-graphql",
    kind: "backend",
    label: "GraphQL (Apollo)",
    tech: "Apollo Server",
    description: "API graph schema-first",
    category: "framework",
    popularity: 7,
    defaults: { framework: "Apollo Server" },
  },
  {
    id: "be-grpc",
    kind: "backend",
    label: "gRPC",
    tech: "gRPC",
    description: "RPC binário de alta perf",
    category: "framework",
    popularity: 6,
    defaults: { framework: "gRPC" },
  },
  {
    id: "db-postgres",
    kind: "database",
    label: "PostgreSQL",
    tech: "PostgreSQL",
    description: "Relacional robusto",
    category: "database",
    popularity: 10,
    defaults: { engine: "PostgreSQL" },
    ha_model: "multi-az",
    pricing_tier: "standard",
    regions: ["us-east-1", "us-west-2", "eu-west-1", "ap-southeast-1"],
    sla_pct: 99.99,
    rps_guidance: "10k+ RPS para workloads OLTP",
    limits: { max_rps: 50000, max_connections: 10000, max_throughput_mbps: 1000 },
  },
  {
    id: "db-mysql",
    kind: "database",
    label: "MySQL",
    tech: "MySQL",
    description: "Relacional popular",
    category: "database",
    popularity: 8,
    defaults: { engine: "MySQL" },
  },
  {
    id: "db-mariadb",
    kind: "database",
    label: "MariaDB",
    tech: "MariaDB",
    description: "Fork do MySQL",
    category: "database",
    popularity: 5,
    defaults: { engine: "MariaDB" },
  },
  {
    id: "db-mongo",
    kind: "database",
    label: "MongoDB",
    tech: "MongoDB",
    description: "Documentos",
    category: "database",
    popularity: 8,
    defaults: { engine: "MongoDB" },
  },
  {
    id: "db-dynamo",
    kind: "database",
    label: "DynamoDB",
    tech: "DynamoDB",
    description: "NoSQL gerenciado AWS",
    category: "database",
    popularity: 7,
    defaults: { engine: "DynamoDB" },
  },
  {
    id: "db-redis",
    kind: "database",
    label: "Redis",
    tech: "Redis",
    description: "Cache / filas",
    category: "database",
    popularity: 9,
    defaults: { engine: "Redis" },
  },
  {
    id: "db-cassandra",
    kind: "database",
    label: "Cassandra",
    tech: "Cassandra",
    description: "Wide-column escala",
    category: "database",
    popularity: 5,
    defaults: { engine: "Cassandra" },
  },
  {
    id: "db-clickhouse",
    kind: "database",
    label: "ClickHouse",
    tech: "ClickHouse",
    description: "OLAP colunar, analytics",
    category: "database",
    popularity: 6,
    defaults: { engine: "ClickHouse" },
  },
  {
    id: "db-elasticsearch",
    kind: "database",
    label: "Elasticsearch",
    tech: "Elasticsearch",
    description: "Full-text search / logs",
    category: "database",
    popularity: 7,
    defaults: { engine: "Elasticsearch" },
  },
  {
    id: "db-influx",
    kind: "database",
    label: "InfluxDB",
    tech: "InfluxDB",
    description: "Time-series / métricas",
    category: "database",
    popularity: 5,
    defaults: { engine: "InfluxDB" },
  },
  {
    id: "db-surrealdb",
    kind: "database",
    label: "SurrealDB",
    tech: "SurrealDB",
    description: "Multi-model, SQL-like",
    category: "database",
    popularity: 3,
    defaults: { engine: "SurrealDB" },
  },
  {
    id: "db-cockroach",
    kind: "database",
    label: "CockroachDB",
    tech: "CockroachDB",
    description: "Distribuído, compatível PG",
    category: "database",
    popularity: 4,
    defaults: { engine: "CockroachDB" },
  },
  {
    id: "db-supabase",
    kind: "database",
    label: "Supabase",
    tech: "Supabase",
    description: "Postgres + Auth + Storage",
    category: "platform",
    popularity: 7,
    defaults: { engine: "Supabase" },
  },
  {
    id: "db-convex",
    kind: "database",
    label: "Convex",
    tech: "Convex",
    description: "DB reativo real-time",
    category: "platform",
    popularity: 4,
    defaults: { engine: "Convex" },
  },
  {
    id: "db-planetscale",
    kind: "database",
    label: "PlanetScale",
    tech: "PlanetScale",
    description: "Serverless MySQL branching",
    category: "platform",
    popularity: 5,
    defaults: { engine: "PlanetScale" },
  },
  {
    id: "db-neon",
    kind: "database",
    label: "Neon",
    tech: "Neon",
    description: "Postgres serverless branching",
    category: "platform",
    popularity: 5,
    defaults: { engine: "Neon" },
  },
  {
    id: "cloud-aws-ec2",
    kind: "cloud",
    label: "EC2",
    tech: "AWS EC2",
    description: "Compute · VM sob demanda",
    category: "service",
    popularity: 9,
    layer: "compute",
    defaults: { provider: "AWS", service: "EC2", layer: "compute" },
  },
  {
    id: "cloud-aws-ecs",
    kind: "cloud",
    label: "ECS",
    tech: "AWS ECS",
    description: "Compute · containers gerenciados",
    category: "service",
    popularity: 7,
    layer: "compute",
    defaults: { provider: "AWS", service: "ECS", layer: "compute" },
  },
  {
    id: "cloud-aws-lambda",
    kind: "cloud",
    label: "Lambda",
    tech: "AWS Lambda",
    description: "Compute · serverless",
    category: "service",
    popularity: 8,
    layer: "compute",
    defaults: { provider: "AWS", service: "Lambda", layer: "compute" },
  },
  {
    id: "cloud-aws-s3",
    kind: "cloud",
    label: "S3",
    tech: "AWS S3",
    description: "Data · object storage",
    category: "service",
    popularity: 10,
    layer: "data",
    defaults: { provider: "AWS", service: "S3", layer: "data" },
  },
  {
    id: "cloud-aws-rds",
    kind: "cloud",
    label: "RDS",
    tech: "AWS RDS",
    description: "Data · banco gerenciado",
    category: "service",
    popularity: 8,
    layer: "data",
    defaults: { provider: "AWS", service: "RDS", layer: "data" },
  },
  {
    id: "cloud-aws-cf",
    kind: "cloud",
    label: "CloudFront",
    tech: "AWS CloudFront",
    description: "Edge · CDN",
    category: "service",
    popularity: 7,
    layer: "edge",
    defaults: { provider: "AWS", service: "CloudFront", layer: "edge" },
  },
  {
    id: "cloud-aws-alb",
    kind: "cloud",
    label: "Load Balancer",
    tech: "AWS ALB",
    description: "Edge · balanceamento L7",
    category: "service",
    popularity: 7,
    layer: "edge",
    defaults: { provider: "AWS", service: "Load Balancer", layer: "edge" },
  },
  {
    id: "cloud-aws-apigw",
    kind: "cloud",
    label: "API Gateway",
    tech: "AWS API Gateway",
    description: "Edge · porta de entrada HTTP",
    category: "service",
    popularity: 6,
    layer: "edge",
    defaults: { provider: "AWS", service: "API Gateway", layer: "edge" },
  },
  {
    id: "cloud-aws-elasticache",
    kind: "cloud",
    label: "ElastiCache",
    tech: "AWS ElastiCache",
    description: "Data · Redis/Memcached gerenciado",
    category: "service",
    popularity: 6,
    layer: "data",
    defaults: { provider: "AWS", service: "ElastiCache", layer: "data" },
  },
  {
    id: "cloud-azure",
    kind: "cloud",
    label: "Azure App Service",
    tech: "Azure",
    description: "Platform · PaaS Microsoft",
    category: "platform",
    popularity: 7,
    layer: "platform",
    defaults: { provider: "Azure", service: "App Service", layer: "platform" },
  },
  {
    id: "cloud-gcp",
    kind: "cloud",
    label: "Cloud Run",
    tech: "Google Cloud",
    description: "Compute · containers no GCP",
    category: "platform",
    popularity: 7,
    layer: "compute",
    defaults: { provider: "Google Cloud", service: "Cloud Run", layer: "compute" },
  },
  {
    id: "cloud-do",
    kind: "cloud",
    label: "DigitalOcean",
    tech: "DigitalOcean",
    description: "Compute · Droplets simples",
    category: "platform",
    popularity: 6,
    layer: "compute",
    defaults: { provider: "Digital Ocean", service: "Droplet", layer: "compute" },
  },
  {
    id: "cloud-hostinger",
    kind: "cloud",
    label: "Hostinger VPS",
    tech: "Hostinger VPS",
    description: "Compute · VPS barato",
    category: "platform",
    popularity: 4,
    layer: "compute",
    defaults: { provider: "Hostinger VPS", service: "VPS", layer: "compute" },
  },
  {
    id: "cloud-vercel",
    kind: "cloud",
    label: "Vercel",
    tech: "Vercel",
    description: "Platform · deploy Next.js",
    category: "platform",
    popularity: 8,
    layer: "platform",
    defaults: { provider: "Vercel", service: "Vercel", layer: "platform" },
  },
  {
    id: "cloud-cf-workers",
    kind: "cloud",
    label: "Cloudflare Workers",
    tech: "Cloudflare",
    description: "Compute · edge serverless",
    category: "service",
    popularity: 6,
    layer: "edge",
    defaults: { provider: "Cloudflare", service: "Workers", layer: "edge" },
  },
  {
    id: "cloud-railway",
    kind: "cloud",
    label: "Railway",
    tech: "Railway",
    description: "Platform · deploy rápido",
    category: "platform",
    popularity: 5,
    layer: "platform",
    defaults: { provider: "Railway", service: "Railway", layer: "platform" },
  },
  {
    id: "cloud-render",
    kind: "cloud",
    label: "Render",
    tech: "Render",
    description: "Platform · web services",
    category: "platform",
    popularity: 5,
    layer: "platform",
    defaults: { provider: "Render", service: "Render", layer: "platform" },
  },
  {
    id: "cloud-flyio",
    kind: "cloud",
    label: "Fly.io",
    tech: "Fly.io",
    description: "Compute · apps globais",
    category: "platform",
    popularity: 5,
    layer: "compute",
    defaults: { provider: "Fly.io", service: "Fly.io", layer: "compute" },
  },
  {
    id: "cloud-docker",
    kind: "cloud",
    label: "Docker",
    tech: "Docker",
    description: "Containers padronizados",
    category: "tool",
    popularity: 10,
    layer: "compute",
    defaults: { provider: "Docker", service: "Docker", layer: "compute" },
  },
  {
    id: "cloud-k8s",
    kind: "cloud",
    label: "Kubernetes",
    tech: "Kubernetes",
    description: "Orquestração de containers",
    category: "tool",
    popularity: 8,
    layer: "compute",
    defaults: { provider: "Kubernetes", service: "K8s", layer: "compute" },
  },
  {
    id: "cloud-terraform",
    kind: "cloud",
    label: "Terraform",
    tech: "Terraform",
    description: "IaC · infra como código",
    category: "tool",
    popularity: 7,
    layer: "platform",
    defaults: { provider: "HashiCorp", service: "Terraform", layer: "platform" },
  },
  {
    id: "cloud-coolify",
    kind: "cloud",
    label: "Coolify",
    tech: "Coolify",
    description: "Self-hosted PaaS",
    category: "platform",
    popularity: 4,
    layer: "platform",
    defaults: { provider: "Coolify", service: "Coolify", layer: "platform" },
  },
  // ── Integrações: Filas / Messaging ──
  {
    id: "int-rabbit",
    kind: "integration",
    label: "RabbitMQ",
    tech: "RabbitMQ",
    description: "Filas AMQP clássicas",
    category: "service",
    popularity: 7,
    tags: ["fila", "amqp", "async"],
    defaults: { service: "RabbitMQ" },
  },
  {
    id: "int-sqs",
    kind: "integration",
    label: "SQS",
    tech: "AWS SQS",
    description: "Fila gerenciada AWS",
    category: "service",
    popularity: 7,
    tags: ["fila", "aws", "async"],
    defaults: { provider: "AWS", service: "SQS" },
  },
  {
    id: "int-kafka",
    kind: "integration",
    label: "Kafka",
    tech: "Apache Kafka",
    description: "Event streaming de alta performance",
    category: "service",
    popularity: 8,
    tags: ["event-streaming", "async", "real-time"],
    defaults: { service: "Kafka" },
  },
  {
    id: "int-redis-streams",
    kind: "integration",
    label: "Redis Streams",
    tech: "Redis Streams",
    description: "Stream leve sobre Redis",
    category: "service",
    popularity: 5,
    tags: ["stream", "redis", "async"],
    defaults: { service: "Redis Streams" },
  },
  {
    id: "int-nats",
    kind: "integration",
    label: "NATS",
    tech: "NATS",
    description: "Messaging ultra leve",
    category: "service",
    popularity: 5,
    tags: ["messaging", "lightweight", "async"],
    defaults: { service: "NATS" },
  },
  {
    id: "int-sns",
    kind: "integration",
    label: "AWS SNS",
    tech: "AWS SNS",
    description: "Pub/sub gerenciado AWS",
    category: "service",
    popularity: 6,
    tags: ["pub-sub", "aws", "notifications"],
    defaults: { provider: "AWS", service: "SNS" },
  },
  {
    id: "int-pulsar",
    kind: "integration",
    label: "Apache Pulsar",
    tech: "Apache Pulsar",
    description: "Event streaming multi-tenant",
    category: "service",
    popularity: 4,
    tags: ["event-streaming", "multi-tenant", "async"],
    defaults: { service: "Pulsar" },
  },
  {
    id: "int-redis-pubsub",
    kind: "integration",
    label: "Redis Pub/Sub",
    tech: "Redis Pub/Sub",
    description: "Pub/sub leve e rápido",
    category: "service",
    popularity: 5,
    tags: ["pub-sub", "redis", "real-time"],
    defaults: { service: "Redis Pub/Sub" },
  },
  // ── Identidade ──
  {
    id: "id-cognito",
    kind: "identity",
    label: "Cognito",
    tech: "AWS Cognito",
    description: "Auth gerenciada AWS",
    category: "service",
    popularity: 6,
    defaults: { provider: "AWS", service: "Cognito" },
  },
  {
    id: "id-auth0",
    kind: "identity",
    label: "Auth0",
    tech: "Auth0",
    description: "IdP comercial",
    category: "service",
    popularity: 7,
    defaults: { service: "Auth0" },
  },
  {
    id: "id-keycloak",
    kind: "identity",
    label: "Keycloak",
    tech: "Keycloak",
    description: "IdP open-source",
    category: "service",
    popularity: 6,
    defaults: { service: "Keycloak" },
  },
  {
    id: "id-jwt",
    kind: "identity",
    label: "JWT / sessão própria",
    tech: "JWT",
    description: "Auth no próprio backend",
    category: "library",
    popularity: 8,
    defaults: { service: "JWT" },
  },
  {
    id: "id-firebase",
    kind: "identity",
    label: "Firebase Auth",
    tech: "Firebase",
    description: "Auth Google/social fácil",
    category: "service",
    popularity: 7,
    defaults: { provider: "Google", service: "Firebase Auth" },
  },
  {
    id: "id-supabase-auth",
    kind: "identity",
    label: "Supabase Auth",
    tech: "Supabase",
    description: "Auth integrada ao Supabase",
    category: "service",
    popularity: 6,
    defaults: { provider: "Supabase", service: "Supabase Auth" },
  },
  {
    id: "id-clerk",
    kind: "identity",
    label: "Clerk",
    tech: "Clerk",
    description: "Auth embeddable moderna",
    category: "service",
    popularity: 6,
    defaults: { service: "Clerk" },
  },
  {
    id: "id-ory",
    kind: "identity",
    label: "Ory",
    tech: "Ory",
    description: "IdP open-source distribuído",
    category: "service",
    popularity: 4,
    defaults: { service: "Ory" },
  },
  // ── Observabilidade ──
  {
    id: "obs-prometheus",
    kind: "observability",
    label: "Prometheus",
    tech: "Prometheus",
    description: "Métricas",
    category: "tool",
    popularity: 8,
    defaults: { service: "Prometheus" },
  },
  {
    id: "obs-grafana",
    kind: "observability",
    label: "Grafana",
    tech: "Grafana",
    description: "Dashboards",
    category: "tool",
    popularity: 8,
    defaults: { service: "Grafana" },
  },
  {
    id: "obs-otel",
    kind: "observability",
    label: "OpenTelemetry",
    tech: "OpenTelemetry",
    description: "Tracing / telemetria",
    category: "tool",
    popularity: 7,
    defaults: { service: "OpenTelemetry" },
  },
  {
    id: "obs-sentry",
    kind: "observability",
    label: "Sentry",
    tech: "Sentry",
    description: "Erros de aplicação",
    category: "service",
    popularity: 8,
    defaults: { service: "Sentry" },
  },
  {
    id: "obs-cloudwatch",
    kind: "observability",
    label: "CloudWatch",
    tech: "AWS CloudWatch",
    description: "Logs/métricas AWS",
    category: "service",
    popularity: 6,
    defaults: { provider: "AWS", service: "CloudWatch" },
  },
  {
    id: "obs-datadog",
    kind: "observability",
    label: "Datadog",
    tech: "Datadog",
    description: "APM + métricas + logs",
    category: "service",
    popularity: 7,
    defaults: { service: "Datadog" },
  },
  {
    id: "obs-newrelic",
    kind: "observability",
    label: "New Relic",
    tech: "New Relic",
    description: "APM full-stack",
    category: "service",
    popularity: 6,
    defaults: { service: "New Relic" },
  },
  {
    id: "obs-jaeger",
    kind: "observability",
    label: "Jaeger",
    tech: "Jaeger",
    description: "Distributed tracing",
    category: "tool",
    popularity: 5,
    defaults: { service: "Jaeger" },
  },
  {
    id: "obs-loki",
    kind: "observability",
    label: "Loki",
    tech: "Grafana Loki",
    description: "Logs indexados leve",
    category: "tool",
    popularity: 6,
    defaults: { service: "Loki" },
  },
  {
    id: "obs-uptimekuma",
    kind: "observability",
    label: "Uptime Kuma",
    tech: "Uptime Kuma",
    description: "Status page self-hosted",
    category: "tool",
    popularity: 5,
    defaults: { service: "Uptime Kuma" },
  },
  // ── Integrações ──
  {
    id: "int-stripe",
    kind: "integration",
    label: "Stripe",
    tech: "Stripe",
    description: "Pagamentos",
    category: "service",
    popularity: 9,
    defaults: { service: "Stripe" },
  },
  {
    id: "int-mercadopago",
    kind: "integration",
    label: "Mercado Pago",
    tech: "Mercado Pago",
    description: "Pagamentos BR",
    category: "service",
    popularity: 6,
    defaults: { service: "Mercado Pago" },
  },
  {
    id: "int-sendgrid",
    kind: "integration",
    label: "SendGrid",
    tech: "SendGrid",
    description: "E-mail transacional",
    category: "service",
    popularity: 7,
    defaults: { service: "SendGrid" },
  },
  {
    id: "int-whatsapp",
    kind: "integration",
    label: "WhatsApp API",
    tech: "WhatsApp",
    description: "Mensagens / Evolution",
    category: "service",
    popularity: 6,
    defaults: { service: "WhatsApp" },
  },
  {
    id: "int-webhook",
    kind: "integration",
    label: "Webhooks",
    tech: "Webhooks",
    description: "Entrada/saída de eventos",
    category: "tool",
    popularity: 7,
    defaults: { service: "Webhooks" },
  },
  {
    id: "int-twilio",
    kind: "integration",
    label: "Twilio",
    tech: "Twilio",
    description: "SMS / voz / WhatsApp",
    category: "service",
    popularity: 7,
    defaults: { service: "Twilio" },
  },
  {
    id: "int-ses",
    kind: "integration",
    label: "AWS SES",
    tech: "AWS SES",
    description: "E-mail transacional barato",
    category: "service",
    popularity: 6,
    defaults: { provider: "AWS", service: "SES" },
  },
  {
    id: "int-plausible",
    kind: "integration",
    label: "Plausible",
    tech: "Plausible",
    description: "Analytics privacidade",
    category: "service",
    popularity: 5,
    defaults: { service: "Plausible" },
  },
  {
    id: "int-posthog",
    kind: "integration",
    label: "PostHog",
    tech: "PostHog",
    description: "Analytics + feature flags",
    category: "service",
    popularity: 6,
    defaults: { service: "PostHog" },
  },
  {
    id: "int-resend",
    kind: "integration",
    label: "Resend",
    tech: "Resend",
    description: "E-mail devs moderno",
    category: "service",
    popularity: 5,
    defaults: { service: "Resend" },
  },
  {
    id: "int-n8n",
    kind: "integration",
    label: "n8n",
    tech: "n8n",
    description: "Automação visual workflows",
    category: "tool",
    popularity: 5,
    defaults: { service: "n8n" },
  },
  {
    id: "int-linear",
    kind: "integration",
    label: "Linear",
    tech: "Linear",
    description: "Gestão de projetos ágil",
    category: "service",
    popularity: 5,
    defaults: { service: "Linear" },
  },
  {
    id: "int-github",
    kind: "integration",
    label: "GitHub Actions",
    tech: "GitHub Actions",
    description: "CI/CD integrado ao repo",
    category: "service",
    popularity: 9,
    defaults: { service: "GitHub Actions" },
  },
  // ===== Linguagens de programacao =====
  {
    id: "lang-typescript",
    kind: "frontend",
    label: "TypeScript",
    tech: "TypeScript",
    description: "JavaScript tipado",
    category: "language",
    popularity: 10,
    tags: ["ts", "js", "javascript"],
    defaults: { framework: "TypeScript" },
  },
  {
    id: "lang-javascript",
    kind: "frontend",
    label: "JavaScript",
    tech: "JavaScript",
    description: "Linguagem da web",
    category: "language",
    popularity: 10,
    tags: ["js", "ecmascript"],
    defaults: { framework: "JavaScript" },
  },
  {
    id: "lang-python",
    kind: "backend",
    label: "Python",
    tech: "Python",
    description: "Propósito geral, IA/ML, backend",
    category: "language",
    popularity: 10,
    tags: ["py", "django", "flask", "fastapi"],
    defaults: { framework: "Python" },
  },
  {
    id: "lang-go",
    kind: "backend",
    label: "Go",
    tech: "Go",
    description: "Concorrência, cloud native",
    category: "language",
    popularity: 8,
    tags: ["golang"],
    defaults: { framework: "Go" },
  },
  {
    id: "lang-rust",
    kind: "backend",
    label: "Rust",
    tech: "Rust",
    description: "Performance, segurança de memória",
    category: "language",
    popularity: 7,
    tags: ["systems"],
    defaults: { framework: "Rust" },
  },
  {
    id: "lang-java",
    kind: "backend",
    label: "Java",
    tech: "Java",
    description: "Enterprise, JVM",
    category: "language",
    popularity: 9,
    tags: ["jvm", "spring", "enterprise"],
    defaults: { framework: "Java" },
  },
  {
    id: "lang-csharp",
    kind: "backend",
    label: "C#",
    tech: "C#",
    description: ".NET, enterprise Microsoft",
    category: "language",
    popularity: 7,
    tags: ["dotnet", ".net"],
    defaults: { framework: "C#" },
  },
  {
    id: "lang-ruby",
    kind: "backend",
    label: "Ruby",
    tech: "Ruby",
    description: "Developer happiness, Rails",
    category: "language",
    popularity: 5,
    tags: ["rails"],
    defaults: { framework: "Ruby" },
  },
  {
    id: "lang-php",
    kind: "backend",
    label: "PHP",
    tech: "PHP",
    description: "Web server-side clássico",
    category: "language",
    popularity: 6,
    tags: ["laravel", "wordpress"],
    defaults: { framework: "PHP" },
  },
  {
    id: "lang-elixir",
    kind: "backend",
    label: "Elixir",
    tech: "Elixir",
    description: "BEAM VM, real-time",
    category: "language",
    popularity: 4,
    tags: ["phoenix", "beam", "erlang"],
    defaults: { framework: "Elixir" },
  },
  {
    id: "lang-kotlin",
    kind: "backend",
    label: "Kotlin",
    tech: "Kotlin",
    description: "JVM moderno, Android",
    category: "language",
    popularity: 7,
    tags: ["jvm", "android"],
    defaults: { framework: "Kotlin" },
  },
  {
    id: "lang-swift",
    kind: "frontend",
    label: "Swift",
    tech: "Swift",
    description: "iOS/macOS nativo",
    category: "language",
    popularity: 7,
    tags: ["ios", "apple", "mobile"],
    defaults: { framework: "Swift" },
  },
  {
    id: "lang-dart",
    kind: "frontend",
    label: "Dart",
    tech: "Dart",
    description: "Flutter, mobile cross-platform",
    category: "language",
    popularity: 7,
    tags: ["flutter", "mobile"],
    defaults: { framework: "Dart" },
  },
  // ===== Mobile frameworks =====
  {
    id: "fe-flutter",
    kind: "frontend",
    label: "Flutter",
    tech: "Flutter",
    description: "Cross-platform mobile/web/desktop",
    category: "framework",
    popularity: 8,
    tags: ["dart", "mobile", "app"],
    defaults: { framework: "Flutter", rendering: "CSR" },
  },
  {
    id: "fe-reactnative",
    kind: "frontend",
    label: "React Native",
    tech: "React Native",
    description: "Mobile nativo com React",
    category: "framework",
    popularity: 8,
    tags: ["mobile", "app", "javascript"],
    defaults: { framework: "React Native", rendering: "CSR" },
  },
  {
    id: "fe-expo",
    kind: "frontend",
    label: "Expo",
    tech: "Expo",
    description: "React Native turbinado",
    category: "framework",
    popularity: 7,
    tags: ["mobile", "app", "react-native"],
    defaults: { framework: "Expo", rendering: "CSR" },
  },
  {
    id: "fe-ionic",
    kind: "frontend",
    label: "Ionic",
    tech: "Ionic",
    description: "Hybrid mobile com web tech",
    category: "framework",
    popularity: 4,
    tags: ["mobile", "app", "hybrid"],
    defaults: { framework: "Ionic", rendering: "CSR" },
  },
  // ===== Bibliotecas populares =====
  {
    id: "lib-tailwind",
    kind: "frontend",
    label: "Tailwind CSS",
    tech: "Tailwind",
    description: "Utility-first CSS",
    category: "library",
    popularity: 10,
    tags: ["css", "ui", "styling"],
    defaults: { uiLib: "Tailwind" },
  },
  {
    id: "lib-shadcn",
    kind: "frontend",
    label: "shadcn/ui",
    tech: "shadcn/ui",
    description: "Components Radix + Tailwind",
    category: "library",
    popularity: 9,
    tags: ["ui", "components", "radix"],
    defaults: { uiLib: "shadcn/ui" },
  },
  {
    id: "lib-prisma",
    kind: "backend",
    label: "Prisma",
    tech: "Prisma",
    description: "ORM TypeScript/Node",
    category: "library",
    popularity: 8,
    tags: ["orm", "database", "typescript"],
    defaults: { framework: "Prisma" },
  },
  {
    id: "lib-drizzle",
    kind: "backend",
    label: "Drizzle ORM",
    tech: "Drizzle",
    description: "ORM SQL-like, leve",
    category: "library",
    popularity: 7,
    tags: ["orm", "database", "typescript"],
    defaults: { framework: "Drizzle" },
  },
  {
    id: "lib-sqlalchemy",
    kind: "backend",
    label: "SQLAlchemy",
    tech: "SQLAlchemy",
    description: "ORM Python robusto",
    category: "library",
    popularity: 8,
    tags: ["orm", "database", "python"],
    defaults: { framework: "SQLAlchemy" },
  },
  {
    id: "lib-trpc",
    kind: "backend",
    label: "tRPC",
    tech: "tRPC",
    description: "RPC type-safe end-to-end",
    category: "library",
    popularity: 7,
    tags: ["typescript", "api", "fullstack"],
    defaults: { framework: "tRPC" },
  },
  {
    id: "lib-zustand",
    kind: "frontend",
    label: "Zustand",
    tech: "Zustand",
    description: "State management minimalista",
    category: "library",
    popularity: 8,
    tags: ["state", "react"],
    defaults: { state: "Zustand" },
  },
  {
    id: "lib-tanstack",
    kind: "frontend",
    label: "TanStack Query",
    tech: "TanStack Query",
    description: "Data fetching + cache",
    category: "library",
    popularity: 9,
    tags: ["react-query", "data", "cache"],
    defaults: { framework: "TanStack Query" },
  },
  {
    id: "lib-socketio",
    kind: "backend",
    label: "Socket.IO",
    tech: "Socket.IO",
    description: "WebSocket real-time",
    category: "library",
    popularity: 7,
    tags: ["websocket", "realtime"],
    defaults: { framework: "Socket.IO" },
  },
  {
    id: "lib-celery",
    kind: "backend",
    label: "Celery",
    tech: "Celery",
    description: "Task queue Python",
    category: "library",
    popularity: 7,
    tags: ["queue", "async", "python"],
    defaults: { framework: "Celery" },
  },
  {
    id: "lib-bullmq",
    kind: "backend",
    label: "BullMQ",
    tech: "BullMQ",
    description: "Job queue Node.js + Redis",
    category: "library",
    popularity: 6,
    tags: ["queue", "jobs", "redis"],
    defaults: { framework: "BullMQ" },
  },
  // ── Deploy ──
  {
    id: "dep-docker",
    kind: "deploy",
    label: "Docker",
    tech: "Docker",
    description: "Packaging and distribution of applications in containers",
    category: "tool",
    popularity: 10,
    tags: ["containers", "packaging", "devops"],
    defaults: { service: "Docker" },
  },
  {
    id: "dep-compose",
    kind: "deploy",
    label: "Docker Compose",
    tech: "Docker Compose",
    description: "Multi-container application orchestration",
    category: "tool",
    popularity: 9,
    tags: ["containers", "orchestration", "multi-service"],
    defaults: { service: "Docker Compose" },
  },
  {
    id: "dep-k8s",
    kind: "deploy",
    label: "Kubernetes",
    tech: "Kubernetes",
    description: "Container orchestration at scale",
    category: "platform",
    popularity: 9,
    tags: ["containers", "orchestration", "scaling", "cloud-native"],
    defaults: { service: "Kubernetes" },
  },
  {
    id: "dep-coolify",
    kind: "deploy",
    label: "Coolify",
    tech: "Coolify",
    description: "Self-hosted PaaS, open-source alternative to Vercel",
    category: "platform",
    popularity: 7,
    tags: ["paas", "self-hosted", "open-source"],
    defaults: { service: "Coolify" },
  },
  {
    id: "dep-vercel",
    kind: "deploy",
    label: "Vercel",
    tech: "Vercel",
    description: "Cloud platform for frontend frameworks",
    category: "platform",
    popularity: 10,
    tags: ["frontend", "serverless", "edge", "jamstack"],
    defaults: { service: "Vercel" },
  },
  {
    id: "dep-netlify",
    kind: "deploy",
    label: "Netlify",
    tech: "Netlify",
    description: "Web hosting with serverless functions",
    category: "platform",
    popularity: 8,
    tags: ["hosting", "serverless", "jamstack"],
    defaults: { service: "Netlify" },
  },
  {
    id: "dep-railway",
    kind: "deploy",
    label: "Railway",
    tech: "Railway",
    description: "Instant cloud infrastructure deployment",
    category: "platform",
    popularity: 7,
    tags: ["paas", "quick-deploy", "databases"],
    defaults: { service: "Railway" },
  },
  {
    id: "dep-flyio",
    kind: "deploy",
    label: "Fly.io",
    tech: "Fly.io",
    description: "Run apps close to users globally",
    category: "platform",
    popularity: 7,
    tags: ["edge", "containers", "global"],
    defaults: { service: "Fly.io" },
  },
  {
    id: "dep-render",
    kind: "deploy",
    label: "Render",
    tech: "Render",
    description: "Unified cloud platform for apps and databases",
    category: "platform",
    popularity: 7,
    tags: ["paas", "databases", "static-sites"],
    defaults: { service: "Render" },
  },
  {
    id: "dep-ghactions",
    kind: "deploy",
    label: "GitHub Actions",
    tech: "GitHub Actions",
    description: "CI/CD workflows integrated with GitHub",
    category: "tool",
    popularity: 10,
    tags: ["ci-cd", "automation", "github"],
    defaults: { service: "GitHub Actions" },
  },
  {
    id: "dep-gitlab-ci",
    kind: "deploy",
    label: "GitLab CI",
    tech: "GitLab CI/CD",
    description: "Built-in CI/CD pipelines for GitLab",
    category: "tool",
    popularity: 8,
    tags: ["ci-cd", "automation", "gitlab"],
    defaults: { service: "GitLab CI" },
  },
  {
    id: "dep-terraform",
    kind: "deploy",
    label: "Terraform",
    tech: "Terraform",
    description: "Infrastructure as Code by HashiCorp",
    category: "tool",
    popularity: 9,
    tags: ["iac", "infrastructure", "multi-cloud"],
    defaults: { service: "Terraform" },
  },
  {
    id: "dep-pulumi",
    kind: "deploy",
    label: "Pulumi",
    tech: "Pulumi",
    description: "IaC using general-purpose programming languages",
    category: "tool",
    popularity: 6,
    tags: ["iac", "infrastructure", "typescript", "python"],
    defaults: { service: "Pulumi" },
  },
  {
    id: "dep-cloudfront",
    kind: "deploy",
    label: "CloudFront CDN",
    tech: "AWS CloudFront",
    description: "Global content delivery network",
    category: "service",
    popularity: 8,
    tags: ["cdn", "cache", "edge", "aws"],
    defaults: { service: "CloudFront" },
  },
  {
    id: "dep-nginx",
    kind: "deploy",
    label: "Nginx",
    tech: "Nginx",
    description: "Reverse proxy, load balancer, and web server",
    category: "tool",
    popularity: 9,
    tags: ["proxy", "load-balancer", "web-server"],
    defaults: { service: "Nginx" },
  },
  {
    id: "dep-traefik",
    kind: "deploy",
    label: "Traefik",
    tech: "Traefik",
    description: "Cloud-native edge router with auto-discovery",
    category: "tool",
    popularity: 7,
    tags: ["proxy", "edge", "docker", "kubernetes"],
    defaults: { service: "Traefik" },
  },

  // ── Security & Infrastructure ───────────────────────────────
  {
    id: "sec-waf",
    kind: "security",
    label: "WAF (Firewall de Aplicação)",
    tech: "WAF",
    description: "Firewall de aplicação web — protege contra SQL injection, XSS e ataques CC",
    category: "security",
    popularity: 9,
    tags: ["security", "waf", "protection"],
    defaults: { provider: "AWS", service: "AWS WAF" },
  },
  {
    id: "sec-ddos",
    kind: "security",
    label: "Proteção DDoS",
    tech: "DDoS Protection",
    description: "Mitigação e proteção contra ataques DDoS",
    category: "security",
    popularity: 8,
    tags: ["security", "ddos", "protection"],
    defaults: { provider: "Cloudflare", service: "Cloudflare DDoS" },
  },
  {
    id: "sec-oidc",
    kind: "security",
    label: "OIDC / OAuth2",
    tech: "OIDC/OAuth2",
    description: "Protocolo de autenticação e autorização de identidade",
    category: "security",
    popularity: 8,
    tags: ["security", "auth", "oauth", "oidc"],
    defaults: { service: "Keycloak" },
  },
  {
    id: "sec-mtls",
    kind: "security",
    label: "mTLS (autenticação mútua)",
    tech: "mTLS",
    description: "TLS mútuo entre serviços — arquitetura zero trust",
    category: "security",
    popularity: 7,
    tags: ["security", "mtls", "zero-trust"],
    defaults: { service: "mTLS" },
  },
  {
    id: "sec-secrets",
    kind: "security",
    label: "Gestão de chaves (KMS)",
    tech: "KMS / Secrets Manager",
    description: "Gestão de chaves de criptografia e credenciais sensíveis",
    category: "security",
    popularity: 8,
    tags: ["security", "kms", "secrets"],
    defaults: { provider: "AWS", service: "AWS KMS" },
  },
  {
    id: "sec-certs",
    kind: "security",
    label: "Certificados TLS",
    tech: "Certificate Manager",
    description: "Emissão e gestão de certificados HTTPS",
    category: "security",
    popularity: 9,
    tags: ["security", "tls", "certificate"],
    defaults: { provider: "AWS", service: "ACM" },
  },
  {
    id: "sec-sg",
    kind: "security",
    label: "Security Group / Network ACL",
    tech: "Security Group",
    description: "Regras de controle de acesso de entrada/saída em hosts na nuvem",
    category: "security",
    popularity: 9,
    tags: ["security", "network", "firewall"],
    defaults: { service: "Security Group" },
  },
  // P2.3.1 — rede completa
  {
    id: "net-tgw",
    kind: "integration" as const,
    label: "Transit Gateway",
    tech: "TGW",
    description: "Hub central para conectar VPCs, VPNs e on-premises em escala",
    category: "network",
    popularity: 8,
    tags: ["network", "tgw", "hub", "transit"],
    defaults: { provider: "AWS", service: "EC2 Transit Gateway" },
  },

  ...MULTI_CLOUD_CATALOG,
  ...PATTERNS_CATALOG,
  ...NETWORK_CATALOG,
];

export const UI_LIBS = ["Tailwind", "Material UI", "Chakra UI", "Design System próprio"];
export const STATE_LIBS = ["Redux", "Zustand", "Context API"];
export const RENDER_MODES = ["SSR", "CSR", "SSG"];

export function catalogByKind(kind: NodeKind): CatalogItem[] {
  return CATALOG.filter((item) => item.kind === kind);
}

export function findCatalog(id: string): CatalogItem | undefined {
  return CATALOG.find((item) => item.id === id);
}
