import type { CatalogItem } from "./types";

/** Serviços de rede enterprise (VPN, peering, PrivateLink, ExpressRoute). */
export const NETWORK_CATALOG: CatalogItem[] = [
  {
    id: "net-aws-vpn",
    kind: "cloud",
    label: "AWS Site-to-Site VPN",
    tech: "AWS VPN",
    description: "Túnel IPsec entre VPC e datacenter / outra cloud",
    category: "service",
    popularity: 8,
    provider: "aws",
    capability: "vpn",
    layer: "edge",
    tags: ["network", "vpn", "hybrid"],
    defaults: { provider: "aws", service: "VPN", layer: "edge", capability: "vpn" },
  },
  {
    id: "net-aws-peering",
    kind: "cloud",
    label: "VPC Peering",
    tech: "AWS VPC Peering",
    description: "Conecta duas VPCs na mesma ou em outra conta/região",
    category: "service",
    popularity: 8,
    provider: "aws",
    capability: "peering",
    layer: "platform",
    tags: ["network", "peering", "vpc"],
    defaults: { provider: "aws", service: "VPC Peering", layer: "platform", capability: "peering" },
  },
  {
    id: "net-aws-privatelink",
    kind: "cloud",
    label: "PrivateLink",
    tech: "AWS PrivateLink",
    description: "Acesso privado a serviços sem atravessar a internet",
    category: "service",
    popularity: 9,
    provider: "aws",
    capability: "privatelink",
    layer: "platform",
    tags: ["network", "privatelink", "security"],
    defaults: { provider: "aws", service: "PrivateLink", layer: "platform", capability: "privatelink" },
  },
  {
    id: "net-aws-tgw",
    kind: "cloud",
    label: "Transit Gateway",
    tech: "AWS Transit Gateway",
    description: "Hub de roteamento entre VPCs, VPN e Direct Connect",
    category: "service",
    popularity: 8,
    provider: "aws",
    capability: "transit",
    layer: "platform",
    tags: ["network", "tgw", "hub"],
    defaults: { provider: "aws", service: "Transit Gateway", layer: "platform", capability: "transit" },
  },
  {
    id: "net-aws-dx",
    kind: "cloud",
    label: "Direct Connect",
    tech: "AWS Direct Connect",
    description: "Link dedicado on-premises → AWS",
    category: "service",
    popularity: 7,
    provider: "aws",
    capability: "express_route",
    layer: "edge",
    tags: ["network", "hybrid", "dedicated"],
    defaults: { provider: "aws", service: "Direct Connect", layer: "edge", capability: "express_route" },
  },
  {
    id: "net-aws-nat",
    kind: "cloud",
    label: "NAT Gateway",
    tech: "AWS NAT Gateway",
    description: "Saída para internet a partir de subnet privada",
    category: "service",
    popularity: 8,
    provider: "aws",
    capability: "nat",
    layer: "edge",
    tags: ["network", "nat", "egress"],
    defaults: { provider: "aws", service: "NAT Gateway", layer: "edge", capability: "nat" },
  },
  {
    id: "net-azure-vpn",
    kind: "cloud",
    label: "Azure VPN Gateway",
    tech: "Azure VPN",
    description: "VPN site-to-site / point-to-site na VNet",
    category: "service",
    popularity: 7,
    provider: "azure",
    capability: "vpn",
    layer: "edge",
    tags: ["network", "vpn", "azure"],
    defaults: { provider: "azure", service: "VPN Gateway", layer: "edge", capability: "vpn" },
  },
  {
    id: "net-azure-er",
    kind: "cloud",
    label: "ExpressRoute",
    tech: "Azure ExpressRoute",
    description: "Circuito privado on-premises → Azure",
    category: "service",
    popularity: 7,
    provider: "azure",
    capability: "express_route",
    layer: "edge",
    tags: ["network", "expressroute", "hybrid"],
    defaults: { provider: "azure", service: "ExpressRoute", layer: "edge", capability: "express_route" },
  },
  {
    id: "net-azure-peering",
    kind: "cloud",
    label: "VNet Peering",
    tech: "Azure VNet Peering",
    description: "Peering privado entre VNets",
    category: "service",
    popularity: 7,
    provider: "azure",
    capability: "peering",
    layer: "platform",
    tags: ["network", "peering", "azure"],
    defaults: { provider: "azure", service: "VNet Peering", layer: "platform", capability: "peering" },
  },
  {
    id: "net-gcp-vpn",
    kind: "cloud",
    label: "Cloud VPN",
    tech: "GCP Cloud VPN",
    description: "VPN HA entre VPC e redes externas",
    category: "service",
    popularity: 6,
    provider: "gcp",
    capability: "vpn",
    layer: "edge",
    tags: ["network", "vpn", "gcp"],
    defaults: { provider: "gcp", service: "Cloud VPN", layer: "edge", capability: "vpn" },
  },
  {
    id: "net-gcp-interconnect",
    kind: "cloud",
    label: "Cloud Interconnect",
    tech: "GCP Interconnect",
    description: "Link dedicado on-premises → GCP",
    category: "service",
    popularity: 6,
    provider: "gcp",
    capability: "express_route",
    layer: "edge",
    tags: ["network", "interconnect", "hybrid"],
    defaults: { provider: "gcp", service: "Cloud Interconnect", layer: "edge", capability: "express_route" },
  },
  // P2.3.1 — rede enterprise completa
  {
    id: "net-nacl",
    kind: "security",
    label: "Network ACL (NACL)",
    tech: "NACL",
    description: "Network ACL stateless — regras de entrada/saída por subnet",
    category: "network",
    popularity: 7,
    tags: ["network", "acl", "nacl", "subnet", "firewall", "stateless"],
    defaults: { service: "NACL" },
  },
  {
    id: "net-prefix",
    kind: "security",
    label: "Prefix List",
    tech: "Prefix List",
    description: "Lista de prefixos CIDR para referência em SG/TGW/VPNGW",
    category: "network",
    popularity: 6,
    tags: ["network", "prefix-list", "ip-range", "cidr", "reference"],
    defaults: { service: "Prefix List" },
  },
  {
    id: "net-dual-stack",
    kind: "network",
    label: "Dual-Stack IPv4/IPv6",
    tech: "Dual-Stack",
    description: "Configuração de rede com endereçamento IPv4 e IPv6 simultâneo",
    category: "network",
    popularity: 7,
    tags: ["network", "ipv6", "dual-stack", "ip", "addressing", "tcp-ip"],
    defaults: { service: "Dual-Stack" },
  },
  // P2.3.2 — segurança completa
  {
    id: "sec-iam-role",
    kind: "identity",
    label: "IAM Role",
    tech: "IAM Role",
    description: "Função de identidade temporária assumida por serviços",
    category: "security",
    popularity: 10,
    tags: ["security", "iam", "role", "assume-role", "sts"],
    defaults: { provider: "aws", service: "IAM Role" },
  },
  {
    id: "sec-iam-policy",
    kind: "security",
    label: "IAM Policy",
    tech: "IAM Policy",
    description: "Política de permissão JSON para IAM (principal ou gerenciada)",
    category: "security",
    popularity: 9,
    tags: ["security", "iam", "policy", "permission", "json", "attach"],
    defaults: { provider: "aws", service: "IAM Policy" },
  },
  {
    id: "sec-encryption",
    kind: "security",
    label: "Encryption at Rest / Transit",
    tech: "Encryption",
    description: "Criptografia de dados em repouso (EBS, RDS) e em trânsito (TLS)",
    category: "security",
    popularity: 10,
    tags: ["security", "encryption", "kms", "tls", "at-rest", "in-transit", "sse"],
    defaults: { provider: "aws", service: "AWS KMS" },
  },
  {
    id: "sec-kms-key",
    kind: "security",
    label: "KMS Customer Master Key",
    tech: "CMK",
    description: "Chave mestra de criptografia gerenciada no KMS",
    category: "security",
    popularity: 8,
    tags: ["security", "kms", "cmk", "encryption", "cryptographic", "key"],
    defaults: { provider: "aws", service: "AWS KMS CMK" },
  },
  {
    id: "sec-guardduty",
    kind: "security",
    label: "GuardDuty / Threat Detection",
    tech: "GuardDuty",
    description: "Detecção de ameaças contínua com ML e feeds de inteligência",
    category: "security",
    popularity: 8,
    tags: ["security", "guardduty", "threat", "detection", "ml", "monitoring"],
    defaults: { provider: "aws", service: "Amazon GuardDuty" },
  },
  {
    id: "sec-config",
    kind: "security",
    label: "Config Recorder / Compliance",
    tech: "Config",
    description: "Avaliação contínua de conformidade de recursos (Config Rules)",
    category: "security",
    popularity: 6,
    tags: ["security", "config", "compliance", "auditing", "drift", "rules"],
    defaults: { provider: "aws", service: "AWS Config" },
  },
];
