import type { CatalogItem } from "./types";

/** Paridade multi-cloud por capability (AWS / Azure / GCP). */
export const MULTI_CLOUD_CATALOG: CatalogItem[] = [
  // DNS
  {
    id: "mc-aws-route53",
    kind: "cloud",
    label: "Route 53",
    tech: "AWS Route 53",
    description: "DNS gerenciado AWS",
    category: "service",
    popularity: 9,
    provider: "aws",
    capability: "dns",
    layer: "edge",
    tags: ["dns", "aws", "edge"],
    defaults: { provider: "aws", service: "Route 53", layer: "edge", capability: "dns" },
  },
  {
    id: "mc-azure-dns",
    kind: "cloud",
    label: "Azure DNS",
    tech: "Azure DNS",
    description: "DNS gerenciado Azure",
    category: "service",
    popularity: 8,
    provider: "azure",
    capability: "dns",
    layer: "edge",
    tags: ["dns", "azure", "edge"],
    defaults: { provider: "azure", service: "Azure DNS", layer: "edge", capability: "dns" },
  },
  {
    id: "mc-gcp-dns",
    kind: "cloud",
    label: "Cloud DNS",
    tech: "GCP Cloud DNS",
    description: "DNS gerenciado GCP",
    category: "service",
    popularity: 8,
    provider: "gcp",
    capability: "dns",
    layer: "edge",
    tags: ["dns", "gcp", "edge"],
    defaults: { provider: "gcp", service: "Cloud DNS", layer: "edge", capability: "dns" },
  },
  // CDN / WAF
  {
    id: "mc-aws-waf",
    kind: "cloud",
    label: "AWS WAF",
    tech: "AWS WAF",
    description: "Web Application Firewall",
    category: "service",
    popularity: 8,
    provider: "aws",
    capability: "cdn_waf",
    layer: "edge",
    tags: ["waf", "security", "aws"],
    defaults: { provider: "aws", service: "WAF", layer: "edge", capability: "cdn_waf" },
  },
  {
    id: "mc-azure-frontdoor",
    kind: "cloud",
    label: "Front Door + WAF",
    tech: "Azure Front Door",
    description: "CDN global + WAF Azure",
    category: "service",
    popularity: 8,
    provider: "azure",
    capability: "cdn_waf",
    layer: "edge",
    tags: ["cdn", "waf", "azure"],
    defaults: { provider: "azure", service: "Front Door", layer: "edge", capability: "cdn_waf" },
  },
  {
    id: "mc-gcp-armor",
    kind: "cloud",
    label: "Cloud Armor + CDN",
    tech: "GCP Cloud Armor",
    description: "WAF + CDN GCP",
    category: "service",
    popularity: 7,
    provider: "gcp",
    capability: "cdn_waf",
    layer: "edge",
    tags: ["waf", "cdn", "gcp"],
    defaults: { provider: "gcp", service: "Cloud Armor", layer: "edge", capability: "cdn_waf" },
  },
  // API edge
  {
    id: "mc-azure-apim",
    kind: "cloud",
    label: "API Management",
    tech: "Azure APIM",
    description: "API Gateway Azure",
    category: "service",
    popularity: 8,
    provider: "azure",
    capability: "api_edge",
    layer: "edge",
    tags: ["api", "gateway", "azure"],
    defaults: { provider: "azure", service: "APIM", layer: "edge", capability: "api_edge" },
  },
  {
    id: "mc-gcp-apigw",
    kind: "cloud",
    label: "API Gateway (GCP)",
    tech: "GCP API Gateway",
    description: "API Gateway / Cloud Endpoints",
    category: "service",
    popularity: 7,
    provider: "gcp",
    capability: "api_edge",
    layer: "edge",
    tags: ["api", "gateway", "gcp"],
    defaults: { provider: "gcp", service: "API Gateway", layer: "edge", capability: "api_edge" },
  },
  // Auth
  {
    id: "mc-azure-entra",
    kind: "identity",
    label: "Entra ID",
    tech: "Microsoft Entra ID",
    description: "Identidade e acesso Azure",
    category: "service",
    popularity: 9,
    provider: "azure",
    capability: "auth",
    tags: ["auth", "identity", "azure"],
    defaults: { provider: "azure", service: "Entra ID", capability: "auth" },
  },
  {
    id: "mc-gcp-identity",
    kind: "identity",
    label: "Identity Platform",
    tech: "GCP Identity Platform",
    description: "Auth gerenciada GCP",
    category: "service",
    popularity: 7,
    provider: "gcp",
    capability: "auth",
    tags: ["auth", "identity", "gcp"],
    defaults: { provider: "gcp", service: "Identity Platform", capability: "auth" },
  },
  // Secrets
  {
    id: "mc-aws-secrets",
    kind: "identity",
    label: "Secrets Manager",
    tech: "AWS Secrets Manager",
    description: "Segredos gerenciados AWS",
    category: "service",
    popularity: 9,
    provider: "aws",
    capability: "secrets",
    tags: ["secrets", "aws", "security"],
    defaults: { provider: "aws", service: "Secrets Manager", capability: "secrets" },
  },
  {
    id: "mc-azure-keyvault",
    kind: "identity",
    label: "Key Vault",
    tech: "Azure Key Vault",
    description: "Segredos e chaves Azure",
    category: "service",
    popularity: 9,
    provider: "azure",
    capability: "secrets",
    tags: ["secrets", "azure", "security"],
    defaults: { provider: "azure", service: "Key Vault", capability: "secrets" },
  },
  {
    id: "mc-gcp-secret",
    kind: "identity",
    label: "Secret Manager",
    tech: "GCP Secret Manager",
    description: "Segredos GCP",
    category: "service",
    popularity: 8,
    provider: "gcp",
    capability: "secrets",
    tags: ["secrets", "gcp", "security"],
    defaults: { provider: "gcp", service: "Secret Manager", capability: "secrets" },
  },
  // Serverless compute
  {
    id: "mc-azure-functions",
    kind: "cloud",
    label: "Azure Functions",
    tech: "Azure Functions",
    description: "Serverless functions Azure",
    category: "service",
    popularity: 9,
    provider: "azure",
    capability: "serverless_compute",
    layer: "compute",
    tags: ["serverless", "faas", "azure"],
    defaults: { provider: "azure", service: "Functions", layer: "compute", capability: "serverless_compute" },
  },
  {
    id: "mc-gcp-functions",
    kind: "cloud",
    label: "Cloud Functions",
    tech: "GCP Cloud Functions",
    description: "Serverless functions GCP",
    category: "service",
    popularity: 8,
    provider: "gcp",
    capability: "serverless_compute",
    layer: "compute",
    tags: ["serverless", "faas", "gcp"],
    defaults: { provider: "gcp", service: "Cloud Functions", layer: "compute", capability: "serverless_compute" },
  },
  // Containers
  {
    id: "mc-azure-containerapps",
    kind: "cloud",
    label: "Container Apps",
    tech: "Azure Container Apps",
    description: "Containers serverless Azure",
    category: "service",
    popularity: 8,
    provider: "azure",
    capability: "containers",
    layer: "compute",
    tags: ["containers", "azure", "fargate"],
    defaults: { provider: "azure", service: "Container Apps", layer: "compute", capability: "containers" },
  },
  {
    id: "mc-gcp-cloudrun",
    kind: "cloud",
    label: "Cloud Run",
    tech: "GCP Cloud Run",
    description: "Containers serverless GCP",
    category: "service",
    popularity: 9,
    provider: "gcp",
    capability: "containers",
    layer: "compute",
    tags: ["containers", "gcp", "serverless"],
    defaults: { provider: "gcp", service: "Cloud Run", layer: "compute", capability: "containers" },
  },
  // Orchestration
  {
    id: "mc-aws-sfn",
    kind: "integration",
    label: "Step Functions",
    tech: "AWS Step Functions",
    description: "Orquestração de workflows AWS",
    category: "service",
    popularity: 8,
    provider: "aws",
    capability: "orchestration",
    tags: ["workflow", "orchestration", "aws"],
    defaults: { provider: "aws", service: "Step Functions", capability: "orchestration" },
  },
  {
    id: "mc-azure-logic",
    kind: "integration",
    label: "Logic Apps",
    tech: "Azure Logic Apps",
    description: "Orquestração / iPaaS Azure",
    category: "service",
    popularity: 7,
    provider: "azure",
    capability: "orchestration",
    tags: ["workflow", "azure"],
    defaults: { provider: "azure", service: "Logic Apps", capability: "orchestration" },
  },
  {
    id: "mc-gcp-workflows",
    kind: "integration",
    label: "Workflows",
    tech: "GCP Workflows",
    description: "Orquestração serverless GCP",
    category: "service",
    popularity: 6,
    provider: "gcp",
    capability: "orchestration",
    tags: ["workflow", "gcp"],
    defaults: { provider: "gcp", service: "Workflows", capability: "orchestration" },
  },
  // Queue / Stream
  {
    id: "mc-azure-eventhubs",
    kind: "integration",
    label: "Event Hubs",
    tech: "Azure Event Hubs",
    description: "Streaming de eventos Azure",
    category: "service",
    popularity: 8,
    provider: "azure",
    capability: "queue_stream",
    tags: ["streaming", "events", "azure", "async"],
    defaults: { provider: "azure", service: "Event Hubs", capability: "queue_stream" },
  },
  {
    id: "mc-azure-servicebus",
    kind: "integration",
    label: "Service Bus",
    tech: "Azure Service Bus",
    description: "Filas e tópicos Azure",
    category: "service",
    popularity: 8,
    provider: "azure",
    capability: "queue_stream",
    tags: ["queue", "azure", "async"],
    defaults: { provider: "azure", service: "Service Bus", capability: "queue_stream" },
  },
  {
    id: "mc-gcp-pubsub",
    kind: "integration",
    label: "Pub/Sub",
    tech: "GCP Pub/Sub",
    description: "Messaging GCP",
    category: "service",
    popularity: 9,
    provider: "gcp",
    capability: "queue_stream",
    tags: ["pubsub", "gcp", "async"],
    defaults: { provider: "gcp", service: "Pub/Sub", capability: "queue_stream" },
  },
  // Object store
  {
    id: "mc-azure-blob",
    kind: "database",
    label: "Blob Storage",
    tech: "Azure Blob Storage",
    description: "Object storage Azure",
    category: "service",
    popularity: 9,
    provider: "azure",
    capability: "object_store",
    tags: ["storage", "blob", "azure"],
    defaults: { provider: "azure", engine: "Blob", capability: "object_store" },
  },
  {
    id: "mc-gcp-gcs",
    kind: "database",
    label: "Cloud Storage",
    tech: "GCP Cloud Storage",
    description: "Object storage GCP",
    category: "service",
    popularity: 9,
    provider: "gcp",
    capability: "object_store",
    tags: ["storage", "gcs", "gcp"],
    defaults: { provider: "gcp", engine: "GCS", capability: "object_store" },
  },
  // NoSQL
  {
    id: "mc-aws-dynamodb",
    kind: "database",
    label: "DynamoDB",
    tech: "AWS DynamoDB",
    description: "NoSQL key-value AWS",
    category: "database",
    popularity: 9,
    provider: "aws",
    capability: "nosql",
    tags: ["nosql", "aws", "dynamodb"],
    defaults: { provider: "aws", engine: "DynamoDB", capability: "nosql" },
  },
  {
    id: "mc-azure-cosmos",
    kind: "database",
    label: "Cosmos DB",
    tech: "Azure Cosmos DB",
    description: "NoSQL multi-modelo Azure",
    category: "database",
    popularity: 8,
    provider: "azure",
    capability: "nosql",
    tags: ["nosql", "azure", "cosmos"],
    defaults: { provider: "azure", engine: "Cosmos DB", capability: "nosql" },
  },
  {
    id: "mc-gcp-firestore",
    kind: "database",
    label: "Firestore",
    tech: "GCP Firestore",
    description: "NoSQL document GCP",
    category: "database",
    popularity: 8,
    provider: "gcp",
    capability: "nosql",
    tags: ["nosql", "gcp", "firestore"],
    defaults: { provider: "gcp", engine: "Firestore", capability: "nosql" },
  },
  // SQL
  {
    id: "mc-azure-mysql",
    kind: "database",
    label: "Azure Database for MySQL",
    tech: "Azure MySQL",
    description: "MySQL gerenciado Azure",
    category: "database",
    popularity: 7,
    provider: "azure",
    capability: "sql",
    tags: ["sql", "mysql", "azure"],
    defaults: { provider: "azure", engine: "MySQL", capability: "sql" },
  },
  {
    id: "mc-gcp-cloudsql",
    kind: "database",
    label: "Cloud SQL",
    tech: "GCP Cloud SQL",
    description: "SQL gerenciado GCP",
    category: "database",
    popularity: 8,
    provider: "gcp",
    capability: "sql",
    tags: ["sql", "gcp"],
    defaults: { provider: "gcp", engine: "Cloud SQL", capability: "sql" },
  },
  // Observability
  {
    id: "mc-aws-cloudwatch",
    kind: "observability",
    label: "CloudWatch",
    tech: "AWS CloudWatch",
    description: "Métricas e logs AWS",
    category: "service",
    popularity: 9,
    provider: "aws",
    capability: "observability",
    tags: ["monitoring", "logs", "aws"],
    defaults: { provider: "aws", service: "CloudWatch", capability: "observability" },
  },
  {
    id: "mc-azure-monitor",
    kind: "observability",
    label: "Azure Monitor",
    tech: "Azure Monitor",
    description: "Observabilidade Azure",
    category: "service",
    popularity: 8,
    provider: "azure",
    capability: "observability",
    tags: ["monitoring", "azure"],
    defaults: { provider: "azure", service: "Monitor", capability: "observability" },
  },
  {
    id: "mc-gcp-monitoring",
    kind: "observability",
    label: "Cloud Monitoring",
    tech: "GCP Cloud Monitoring",
    description: "Observabilidade GCP",
    category: "service",
    popularity: 8,
    provider: "gcp",
    capability: "observability",
    tags: ["monitoring", "gcp"],
    defaults: { provider: "gcp", service: "Cloud Monitoring", capability: "observability" },
  },
  // Authorizer / Lambda authorizer pattern
  {
    id: "mc-aws-lambda-auth",
    kind: "identity",
    label: "Lambda Authorizer",
    tech: "AWS Lambda Authorizer",
    description: "Authorizer custom para API Gateway",
    category: "service",
    popularity: 8,
    provider: "aws",
    capability: "auth",
    tags: ["authorizer", "api", "aws", "lambda"],
    defaults: { provider: "aws", service: "Lambda Authorizer", capability: "auth" },
  },
  // IoT / feedback (load testing)
  {
    id: "mc-aws-iot",
    kind: "integration",
    label: "IoT Core",
    tech: "AWS IoT Core",
    description: "Mensageria IoT / status em tempo real",
    category: "service",
    popularity: 6,
    provider: "aws",
    capability: "realtime_status",
    tags: ["iot", "realtime", "aws"],
    defaults: { provider: "aws", service: "IoT Core", capability: "realtime_status" },
  },
  // ML / BI Azure
  {
    id: "mc-azure-ml",
    kind: "cloud",
    label: "Azure ML",
    tech: "Azure Machine Learning",
    description: "Studio / MLOps Azure",
    category: "service",
    popularity: 7,
    provider: "azure",
    capability: "ml",
    layer: "platform",
    tags: ["ml", "azure"],
    defaults: { provider: "azure", service: "Azure ML", layer: "platform", capability: "ml" },
  },
  {
    id: "mc-azure-powerbi",
    kind: "cloud",
    label: "Power BI",
    tech: "Power BI",
    description: "BI e dashboards",
    category: "service",
    popularity: 9,
    provider: "azure",
    capability: "bi",
    layer: "platform",
    tags: ["bi", "analytics", "azure"],
    defaults: { provider: "azure", service: "Power BI", layer: "platform", capability: "bi" },
  },
  {
    id: "mc-azure-cognitive-text",
    kind: "cloud",
    label: "Text Analytics",
    tech: "Azure AI Language",
    description: "NLP / Text Analytics API",
    category: "service",
    popularity: 7,
    provider: "azure",
    capability: "ai_nlp",
    layer: "platform",
    tags: ["nlp", "cognitive", "azure"],
    defaults: { provider: "azure", service: "Text Analytics", layer: "platform", capability: "ai_nlp" },
  },
];
