import type { CatalogItem } from "./types";

/**
 * Architecture Patterns Library
 * Reusable architectural patterns with metadata for analysis.
 */
export const PATTERNS_CATALOG: CatalogItem[] = [
  // === ARCHITECTURAL PATTERNS ===
  {
    id: "pat-monolith",
    kind: "backend",
    label: "Monolith",
    tech: "Monolithic",
    description: "Single codebase, single deployment unit. Simple but scales poorly.",
    category: "framework",
    popularity: 7,
    tags: ["pattern", "architecture", "simple"],
    defaults: { service: "Monolith" },
  },
  {
    id: "pat-microservices",
    kind: "backend",
    label: "Microservices",
    tech: "Microservices",
    description: "Decoupled services communicating via APIs/events. Complex but scalable.",
    category: "framework",
    popularity: 9,
    tags: ["pattern", "architecture", "scalable"],
    defaults: { service: "Microservices" },
  },
  {
    id: "pat-event-driven",
    kind: "backend",
    label: "Event-Driven",
    tech: "Event-Driven",
    description: "Loosely coupled services via events. Asynchronous, resilient.",
    category: "framework",
    popularity: 8,
    tags: ["pattern", "architecture", "async"],
    defaults: { service: "Event-Driven" },
  },
  {
    id: "pat-cqrs",
    kind: "backend",
    label: "CQRS",
    tech: "CQRS",
    description: "Separate read and write models for independent scaling.",
    category: "framework",
    popularity: 7,
    tags: ["pattern", "cqrs", "read-write"],
    defaults: { service: "CQRS" },
  },
  {
    id: "pat-saga",
    kind: "backend",
    label: "Saga Pattern",
    tech: "Saga",
    description: "Distributed transaction pattern for microservices.",
    category: "framework",
    popularity: 7,
    tags: ["pattern", "transaction", "distributed"],
    defaults: { service: "Saga" },
  },
  {
    id: "pat-strangler",
    kind: "backend",
    label: "Strangler Fig",
    tech: "Strangler Pattern",
    description: "Gradually replace monolith with microservices.",
    category: "framework",
    popularity: 6,
    tags: ["pattern", "migration", "refactor"],
    defaults: { service: "Strangler" },
  },
  {
    id: "pat-sidecar",
    kind: "backend",
    label: "Sidecar",
    tech: "Sidecar Pattern",
    description: "Auxiliary service enhancing primary service (logging, proxy).",
    category: "framework",
    popularity: 6,
    tags: ["pattern", "k8s", "infra"],
    defaults: { service: "Sidecar" },
  },
  {
    id: "pat-bff",
    kind: "backend",
    label: "BFF",
    tech: "Backend for Frontend",
    description: "Dedicated backend per frontend client.",
    category: "framework",
    popularity: 7,
    tags: ["pattern", "bff", "mobile"],
    defaults: { service: "BFF" },
  },
  {
    id: "pat-circuit-breaker",
    kind: "backend",
    label: "Circuit Breaker",
    tech: "Circuit Breaker",
    description: "Fail-fast pattern to prevent cascading failures.",
    category: "framework",
    popularity: 8,
    tags: ["pattern", "resilience", "fault-tolerance"],
    defaults: { service: "Circuit Breaker" },
  },
  {
    id: "pat-rate-limit",
    kind: "backend",
    label: "Rate Limiter",
    tech: "Rate Limiter",
    description: "Control request rates to protect services.",
    category: "framework",
    popularity: 7,
    tags: ["pattern", "protection", "throttling"],
    defaults: { service: "Rate Limiter" },
  },
  {
    id: "pat-outbox",
    kind: "backend",
    label: "Outbox Pattern",
    tech: "Outbox",
    description: "Reliable event publishing with database transaction.",
    category: "framework",
    popularity: 7,
    tags: ["pattern", "reliability", "events"],
    defaults: { service: "Outbox" },
  },
  {
    id: "pat-gateway",
    kind: "backend",
    label: "API Gateway",
    tech: "API Gateway",
    description: "Single entry point for client requests.",
    category: "framework",
    popularity: 9,
    tags: ["pattern", "gateway", "api"],
    defaults: { service: "API Gateway" },
  },
  {
    id: "pat-mesh",
    kind: "backend",
    label: "Service Mesh",
    tech: "Service Mesh",
    description: "Infrastructure layer for service-to-service communication.",
    category: "framework",
    popularity: 7,
    tags: ["pattern", "mesh", "k8s"],
    defaults: { service: "Service Mesh" },
  },
  {
    id: "pat-sharding",
    kind: "database",
    label: "Sharding",
    tech: "Database Sharding",
    description: "Horizontal partitioning of data across multiple databases.",
    category: "service",
    popularity: 7,
    tags: ["pattern", "scaling", "database"],
    defaults: { service: "Sharding" },
  },
  {
    id: "pat-cdc",
    kind: "database",
    label: "CDC",
    tech: "Change Data Capture",
    description: "Capture database changes for replication/events.",
    category: "service",
    popularity: 7,
    tags: ["pattern", "cdc", "replication"],
    defaults: { service: "CDC" },
  },
  {
    id: "pat-lambda-arch",
    kind: "cloud",
    label: "Lambda Architecture",
    tech: "Lambda",
    description: "Batch + speed layers for real-time and historical processing.",
    category: "framework",
    popularity: 6,
    tags: ["pattern", "batch", "streaming"],
    defaults: { service: "Lambda Arch" },
  },
  {
    id: "pat-kappa-arch",
    kind: "cloud",
    label: "Kappa Architecture",
    tech: "Kappa",
    description: "Stream-only processing, simplified Lambda architecture.",
    category: "framework",
    popularity: 5,
    tags: ["pattern", "streaming", "kafka"],
    defaults: { service: "Kappa Arch" },
  },
  {
    id: "pat-heroku",
    kind: "cloud",
    label: "Platform as a Service",
    tech: "PaaS",
    description: "Abstracted infrastructure for faster deployment.",
    category: "platform",
    popularity: 6,
    tags: ["pattern", "paas", "simple"],
    defaults: { service: "PaaS" },
  },

  // === SECURITY PATTERNS ===
  {
    id: "pat-oidc",
    kind: "security",
    label: "OIDC",
    tech: "OpenID Connect",
    description: "Identity layer on top of OAuth 2.0.",
    category: "tool",
    popularity: 8,
    tags: ["pattern", "auth", "oidc"],
    defaults: { service: "OIDC" },
  },
  {
    id: "pat-mtls",
    kind: "security",
    label: "mTLS",
    tech: "Mutual TLS",
    description: "Mutual authentication between services.",
    category: "tool",
    popularity: 7,
    tags: ["pattern", "mtls", "security"],
    defaults: { service: "mTLS" },
  },
  {
    id: "pat-kms",
    kind: "security",
    label: "KMS",
    tech: "Key Management Service",
    description: "Managed encryption key service.",
    category: "service",
    popularity: 8,
    tags: ["pattern", "kms", "encryption"],
    defaults: { service: "KMS" },
  },
  {
    id: "pat-vault",
    kind: "security",
    label: "HashiCorp Vault",
    tech: "Vault",
    description: "Secrets management and encryption as a service.",
    category: "tool",
    popularity: 7,
    tags: ["pattern", "vault", "secrets"],
    defaults: { service: "Vault" },
  },

  // === OBSERVABILITY PATTERNS ===
  {
    id: "pat-distributed-trace",
    kind: "observability",
    label: "Distributed Tracing",
    tech: "OpenTelemetry",
    description: "Trace requests across microservices.",
    category: "tool",
    popularity: 8,
    tags: ["pattern", "observability", "tracing"],
    defaults: { service: "OpenTelemetry" },
  },
  {
    id: "pat-prometheus",
    kind: "observability",
    label: "Prometheus",
    tech: "Prometheus",
    description: "Metrics collection and alerting.",
    category: "tool",
    popularity: 9,
    tags: ["pattern", "metrics", "monitoring"],
    defaults: { service: "Prometheus" },
  },
  {
    id: "pat-grafana",
    kind: "observability",
    label: "Grafana Dashboards",
    tech: "Grafana",
    description: "Visualization for metrics and logs.",
    category: "tool",
    popularity: 9,
    tags: ["pattern", "dashboard", "visualization"],
    defaults: { service: "Grafana" },
  },
  {
    id: "pat-loki",
    kind: "observability",
    label: "Loki Logging",
    tech: "Loki",
    description: "Log aggregation optimized for Prometheus metrics.",
    category: "tool",
    popularity: 7,
    tags: ["pattern", "logging", "loki"],
    defaults: { service: "Loki" },
  },

  // === DATA PATTERNS ===
  {
    id: "pat-event-sourcing",
    kind: "database",
    label: "Event Sourcing",
    tech: "Event Sourcing",
    description: "State derived from immutable event log.",
    category: "framework",
    popularity: 6,
    tags: ["pattern", "events", "immutability"],
    defaults: { service: "Event Sourcing" },
  },
  {
    id: "pat-cdc-pat",
    kind: "database",
    label: "CDC Pattern",
    tech: "CDC",
    description: "Capture database changes for downstream consumers.",
    category: "framework",
    popularity: 6,
    tags: ["pattern", "cdc", "streaming"],
    defaults: { service: "CDC" },
  },
  {
    id: "pat-materialized-view",
    kind: "database",
    label: "Materialized View",
    tech: "Materialized View",
    description: "Pre-computed query results for fast reads.",
    category: "service",
    popularity: 6,
    tags: ["pattern", "performance", "read-optimization"],
    defaults: { service: "Materialized View" },
  },
  {
    id: "pat-cqrs-pat",
    kind: "database",
    label: "CQRS Pattern",
    tech: "CQRS",
    description: "Separate read and write models.",
    category: "framework",
    popularity: 6,
    tags: ["pattern", "cqrs", "scaling"],
    defaults: { service: "CQRS" },
  },

  // === DEPLOY PATTERNS ===
  {
    id: "pat-blue-green",
    kind: "deploy",
    label: "Blue-Green Deploy",
    tech: "Blue-Green",
    description: "Zero-downtime deployment with two environments.",
    category: "tool",
    popularity: 7,
    tags: ["pattern", "deployment", "zero-downtime"],
    defaults: { service: "Blue-Green" },
  },
  {
    id: "pat-canary",
    kind: "deploy",
    label: "Canary Deploy",
    tech: "Canary",
    description: "Gradual rollout to subset of users.",
    category: "tool",
    popularity: 7,
    tags: ["pattern", "deployment", "gradual"],
    defaults: { service: "Canary" },
  },
  {
    id: "pat-iaac",
    kind: "deploy",
    label: "Infrastructure as Code",
    tech: "IaC",
    description: "Manage infrastructure through code.",
    category: "tool",
    popularity: 9,
    tags: ["pattern", "iac", "automation"],
    defaults: { service: "IaC" },
  },
  {
    id: "pat-gitops",
    kind: "deploy",
    label: "GitOps",
    tech: "GitOps",
    description: "Git as single source of truth for deployments.",
    category: "tool",
    popularity: 7,
    tags: ["pattern", "gitops", "automation"],
    defaults: { service: "GitOps" },
  },
];
