import {
  Activity,
  Bell,
  Box,
  Cloud,
  Code,
  Cpu,
  Database,
  FileText,
  Folder,
  Globe,
  HardDrive,
  Heart,
  Key,
  Layers,
  Lock,
  Mail,
  MapPin,
  MessageSquare,
  Package,
  Settings,
  Shield,
  Star,
  Terminal,
  Truck,
  User,
  Users,
  Wifi,
  Zap,
  Server,
  Smartphone,
  type LucideIcon,
} from "lucide-react";

/** Lucide icons available for free-node embedding (P7). */
export const FREE_NODE_ICON_MAP: Record<string, LucideIcon> = {
  user: User,
  users: Users,
  database: Database,
  server: Server,
  cloud: Cloud,
  shield: Shield,
  lock: Lock,
  key: Key,
  zap: Zap,
  settings: Settings,
  mail: Mail,
  message: MessageSquare,
  globe: Globe,
  wifi: Wifi,
  cpu: Cpu,
  harddrive: HardDrive,
  box: Box,
  package: Package,
  layers: Layers,
  folder: Folder,
  file: FileText,
  code: Code,
  terminal: Terminal,
  activity: Activity,
  heart: Heart,
  star: Star,
  bell: Bell,
  map: MapPin,
  truck: Truck,
  smartphone: Smartphone,
};

export const FREE_NODE_ICON_IDS = Object.keys(FREE_NODE_ICON_MAP);

export function resolveFreeIcon(iconId: string | undefined): LucideIcon | null {
  if (!iconId) return null;
  return FREE_NODE_ICON_MAP[iconId] ?? null;
}
