"use client";

import { createElement, type CSSProperties } from "react";
import type { IconType } from "react-icons";
import {
  SiAngular,
  SiApachecassandra,
  SiApachekafka,
  SiAuth0,
  SiBun,
  SiClickhouse,
  SiDart,
  SiDigitalocean,
  SiDjango,
  SiDocker,
  SiElasticsearch,
  SiElixir,
  SiExpo,
  SiExpress,
  SiFastapi,
  SiFlask,
  SiFlutter,
  SiGo,
  SiGooglecloud,
  SiGrafana,
  SiHono,
  SiInfluxdb,
  SiKotlin,
  SiKeycloak,
  SiLaravel,
  SiMariadb,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiOpentelemetry,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiPrometheus,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiRust,
  SiRuby,
  SiSentry,
  SiSocketdotio,
  SiSpringboot,
  SiStripe,
  SiSvelte,
  SiSupabase,
  SiSwift,
  SiTailwindcss,
  SiTypescript,
  SiVuedotjs,
} from "react-icons/si";
import {
  TbBrandAws,
  TbBrandAzure,
  TbBrandCSharp,
  TbBrandJavascript,
  TbBrandVercel,
  TbServer,
} from "react-icons/tb";
import {
  Activity,
  Box,
  Cloud,
  Database,
  Fingerprint,
  Globe,
  Key,
  Layout,
  Mail,
  MessageSquare,
  Monitor,
  Plug,
  Server,
  Shield,
  Workflow,
} from "lucide-react";
import type { NodeKind } from "@/lib/types";

const TECH_ICONS: Record<string, IconType> = {
  "fe-react": SiReact,
  "fe-next": SiNextdotjs,
  "fe-vue": SiVuedotjs,
  "fe-angular": SiAngular,
  "fe-svelte": SiSvelte,
  "be-fastapi": SiFastapi,
  "be-flask": SiFlask,
  "be-django": SiDjango,
  "be-express": SiExpress,
  "be-nest": SiNestjs,
  "be-spring": SiSpringboot,
  "be-laravel": SiLaravel,
  "db-postgres": SiPostgresql,
  "db-mysql": SiMysql,
  "db-mariadb": SiMariadb,
  "db-mongo": SiMongodb,
  "db-redis": SiRedis,
  "db-cassandra": SiApachecassandra,
  "cloud-aws-ec2": TbBrandAws,
  "cloud-aws-ecs": SiDocker,
  "cloud-aws-lambda": TbBrandAws,
  "cloud-aws-s3": TbBrandAws,
  "cloud-aws-rds": TbBrandAws,
  "cloud-aws-cf": TbBrandAws,
  "cloud-aws-alb": TbBrandAws,
  "cloud-aws-apigw": TbBrandAws,
  "cloud-aws-elasticache": SiRedis,
  "cloud-azure": TbBrandAzure,
  "cloud-gcp": SiGooglecloud,
  "cloud-do": SiDigitalocean,
  "cloud-hostinger": TbServer,
  "msg-rabbit": SiRabbitmq,
  "msg-sqs": TbBrandAws,
  "msg-kafka": SiApachekafka,
  "msg-redis-streams": SiRedis,
  "id-cognito": TbBrandAws,
  "id-auth0": SiAuth0,
  "id-keycloak": SiKeycloak,
  "id-jwt": Fingerprint as unknown as IconType,
  "obs-prometheus": SiPrometheus,
  "obs-grafana": SiGrafana,
  "obs-otel": Activity as unknown as IconType,
  "obs-sentry": SiSentry,
  "obs-cloudwatch": TbBrandAws,
  "int-stripe": SiStripe,
  "int-mercadopago": Plug as unknown as IconType,
  "int-sendgrid": Plug as unknown as IconType,
  "int-whatsapp": Plug as unknown as IconType,
  "int-webhook": Workflow as unknown as IconType,
  "lang-typescript": SiTypescript,
  "lang-javascript": TbBrandJavascript as unknown as IconType,
  "lang-python": SiFastapi,
  "lang-go": SiGo,
  "lang-rust": SiRust,
  "lang-java": SiSpringboot,
  "lang-csharp": TbBrandCSharp as unknown as IconType,
  "lang-ruby": SiRuby,
  "lang-php": SiPhp,
  "lang-elixir": SiElixir,
  "lang-kotlin": SiKotlin,
  "lang-swift": SiSwift,
  "lang-dart": SiDart,
  "fe-flutter": SiFlutter,
  "fe-reactnative": SiReact,
  "fe-expo": SiExpo,
  "fe-ionic": SiNodedotjs,
  "lib-tailwind": SiTailwindcss,
  "lib-shadcn": SiReact,
  "lib-prisma": SiPrisma,
  "lib-drizzle": SiPrisma,
  "lib-sqlalchemy": SiPostgresql,
  "lib-trpc": SiTypescript,
  "lib-zustand": SiReact,
  "lib-tanstack": SiReact,
  "lib-socketio": SiSocketdotio,
  "lib-celery": SiNodedotjs,
  "lib-bullmq": SiRedis,
  "be-gin": SiGo,
  "be-actix": SiRust,
  "be-rails": SiRuby,
  "be-dotnet": TbBrandCSharp as unknown as IconType,
  "be-hono": SiHono,
  "be-fiber": SiGo,
  "be-phoenix": SiElixir,
  "be-bun": SiBun,
  "be-denodeploy": SiNodedotjs,
  "be-graphql": Workflow as unknown as IconType,
  "be-grpc": SiNodedotjs,
  "db-dynamo": TbBrandAws,
  "db-clickhouse": SiClickhouse,
  "db-elasticsearch": SiElasticsearch,
  "db-influx": SiInfluxdb,
  "db-surrealdb": SiPostgresql,
  "db-cockroach": SiPostgresql,
  "db-supabase": SiSupabase,
  "db-convex": SiSupabase,
  "db-planetscale": SiMysql,
  "db-neon": SiPostgresql,
  "cloud-vercel": TbBrandVercel as unknown as IconType,
  "cloud-railway": SiDocker,
  "cloud-render": SiDocker,
  "cloud-flyio": SiDocker,
  "cloud-k8s": SiDocker,
  "cloud-terraform": SiNodedotjs,
  "cloud-coolify": SiDocker,
  "msg-nats": SiRabbitmq,
  "msg-sns": TbBrandAws,
  "msg-pulsar": SiApachekafka,
  "msg-redis-pubsub": SiRedis,
  "id-supabase-auth": SiSupabase,
  "id-clerk": Key as unknown as IconType,
  "id-ory": Shield as unknown as IconType,
  "obs-jaeger": SiOpentelemetry,
  "obs-loki": SiGrafana,
  "obs-uptimekuma": Monitor as unknown as IconType,
  "int-twilio": MessageSquare as unknown as IconType,
  "int-ses": Mail as unknown as IconType,
  "int-plausible": Globe as unknown as IconType,
  "int-resend": Mail as unknown as IconType,
  "int-n8n": SiNodedotjs,
  "int-linear": Box as unknown as IconType,
  "int-github": SiNodedotjs,
};

const KIND_FALLBACK: Record<NodeKind, IconType> = {
  frontend: Layout,
  backend: Server,
  database: Database,
  cloud: Cloud,
  messaging: Workflow,
  identity: Fingerprint,
  observability: Activity,
  integration: Plug,
};

export function resolveTechIcon(catalogId: string | undefined, kind: NodeKind): IconType {
  if (catalogId && TECH_ICONS[catalogId]) return TECH_ICONS[catalogId];
  return KIND_FALLBACK[kind];
}

export function TechIcon({
  catalogId,
  kind,
  size = 16,
  className,
  style,
}: {
  catalogId?: string;
  kind: NodeKind;
  size?: number;
  className?: string;
  style?: CSSProperties;
}) {
  return createElement(resolveTechIcon(catalogId, kind), { size, className, style });
}
